### ISSUE TITLE
Project Outline: Features

### ISSUE THREAD

**Issue by lindskelsey** [jcwhite99/liftoff-assignments#2]
Please write 1-2 sentences describing each of your features. Once you've completed this, I will give feedback on the entire project.

**Comment by jcwhite99** [comment]
Hey Lindsay, Just committed my new features list with descriptions.  Sorry it took so long to get this to you.  Hope it makes sense.  I had to write it pretty quick on my lunch.

**Comment by lindskelsey** [comment]
Thanks!
